### ISSUE TITLE
QNAP CPU vs System temperature

### ISSUE THREAD

**Issue by erikschippers** [virus2500/checkmk-qnap#4]
Hi,

I noticed, that the System Temperature and CPU temperature is switched, compared to the output the QNAP provides in the GUI.
So in CMK it shows CPU Temperature on service System
And System temperature on CPU.

I've noticed this on multiple devices, can you check on your system?
(I'm running an older version of the OS, although I didn't find anything on this in the release notes).

Kind Regards,
Erik

**Comment by virus2500** [comment]
Hi,

wow, you have an eagle eye :) I never noticed that. 
Please check out https://github.com/virus2500/checkmk-qnap/releases v1.4.5-alpha1 (under assets you will find the mkp)

It fixed the order for me. Please let me know if it works for you too.

Thanks and best regards
Mike

**Comment by erikschippers** [comment]
Haha that's awesome.
I just checked and uploaded the MKP, it works great now👍.

Thanks for your quick response.
Erik,

**Comment by virus2500** [comment]
Awesome thanks for confirming :)

best regards
